Task23_Low/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Advanced.Controllers
{
    public class GuestController : Controller
    {
        // GET: Guest
        public ActionResult Index()
        {
            return View();
        }
    }
}

Task23_Low/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Advanced.Controllers
{
    public class HomeController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            return View();
        }
       
    }
}

Task23_Low/Controllers/MainController.cs
using System.Web.Mvc;
namespace Task23_Advanced.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            return View("Index");
        }
    }
}

Task23_Low/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Advanced.Controllers
{
    public class QuestionnaireController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Scales = false;
            ViewBag.Horns = false;
            ViewBag.City = false;
            ViewBag.Works = false;
            return View();
        }
        [HttpPost]
        public ActionResult UserPassedData(FormCollection form)
        {
            ViewBag.TextReturn = "Your input fullname: "+ form["Text"];
            ViewBag.AdressReturn = "Your input adress: " + form["Adress"];
            ViewBag.ScalesReturn = "You do not have scales";
            ViewBag.HornsReturn = "You do not have horns";
            ViewBag.RegionReturn = "Your input region: " + form["Region"];
            ViewBag.OrganisationReturn = "Your input organisation: " + form["Organisation"];
            ViewBag.EmailReturn = "Your input email: " + form["Email"];
            if (Convert.ToBoolean(form["Check-box-scales"].Split(',')[0])) 
            {
                ViewBag.ScalesReturn = "You have scales";
            }
            if (Convert.ToBoolean(form["Check-box-horns"].Split(',')[0]))
            {
                ViewBag.HornsReturn = "You have horns";
            }
            ViewBag.CityReturn = "You did not checked city";
                if (form["Check-box-city"]!=null && Convert.ToBoolean(form["Check-box-city"].Split(',')[0]))
                {
                    ViewBag.CityReturn = "You checked city";
                }
            ViewBag.WorkReturn = "You did not checked work";
            if (form["Check-box-work"] != null && Convert.ToBoolean(form["Check-box-work"].Split(',')[0]))
            {
                ViewBag.WorkReturn = "You checked work";
            }
            ViewBag.CountryReturn = "Your input country: " + form["Country"];
            ViewBag.ExperienceReturn = "Your input experience : " + form["Experience"];
            ViewBag.PositionReturn = "Your input position: " + form["Position"];
            return View();
        }
    }
}

Task23_Low/Views/Guest/Index.cshtml
@{
    Layout = "";
    ViewBag.Title = "Guest Page";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet"  href="~/Content/bootstrap.css">
 
    <link rel="stylesheet" href="~/Content/Guest.css" />
</head>
<body>
    <h1>Reviews</h1>
    <div class="container-fluid">
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">22.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">23.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">24.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">25.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">26.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">26.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">26.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>
        <div class="review">
            <div class="author-name">Author:Lorem, ipsum.</div>
            <div class="date">26.08.20</div>
            <div class="review-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eos dolores nobis, ipsa est voluptate accusantium assumenda accusamus necessitatibus eligendi itaque enim voluptates quae reiciendis maiores impedit quia cumque quas ducimus.</div>
        </div>

    </div>

        <form style="background-color:darkgray;">
            <h1 style="font-size:35px;font-weight:600;font-style:italic;">Enter new review</h1>
            <label for="exampleInputEmail1" class="form-label">Enter author name</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter author name" style="font-size:30px;height:50px;width:450px;margin-left:37%;" />


            <label for="exampleInputEmail1" class="form-label">Enter review text</label>
            <textarea type="text" class="form-control" id="exampleInputPassword1" style="width:600px;height:450px; padding-bottom: 400px !important;font-size:20px;margin-left:34%;"></textarea>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

</body>
</html>

Task23_Low/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task23_Low/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task23_Low/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Library";
}

Task23_Low/Views/Home/Main.cshtml
@{
    ViewBag.Title = "Main";
}

<h2>Main</h2>

Task23_Low/Views/Questionnaire/Index.cshtml
@{
    Layout = null;
    ViewBag.Title = "Questionnaire Page";
}
@helper MyInlineHelper(string[] words)
{
    <ol>
        @foreach (string word in words)
        {
            @word
            <li>@Html.TextBox(word)</li>
        }
    </ol>
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Questionnaire.css")
    
</head>
<body>
    @using (Html.BeginForm("UserPassedData", "Questionnaire", FormMethod.Post))
    {
        <div class="form-container">
            @Html.TextBox("Text", ViewBag.Text as string, new { @class = "full-name", @placeholder = "Enter your full name" })
            @Html.TextBox("Adress", ViewBag.Adress as string, new { @class = "adress", @placeholder = "Enter your adress" })
            <p>Choose your features:</p>
            <div class="checkboxes">
                @Html.CheckBox("Check-box-scales", (bool)ViewBag.Scales)
                <label for="scales">Scales</label>
                @Html.CheckBox("Check-box-horns", (bool)ViewBag.Horns)
                <label for="horns">Horns</label>
            </div>

            <div class="switches">
                <label class="switch" id="switch1">
                    @Html.CheckBoxSimple("Check-box-city", new { @class = "switch-input" })

                    <span class="slider"></span>
                </label>
                <label for="switch1">City</label>
                <label class="switch" id="switch2">
                    @Html.CheckBoxSimple("Check-box-work", new { @class = "switch-input" })
                    <span class="slider round"></span>
                </label>
                <label for="switch1">Work</label>
            </div>
            <div class="inline-helper-container">
                @Html.MyInlineHelper(new string[] { "Email", "Organisation", "Region" })
                @MyInlineHelper(new string[] { "Country", "Experience", "Position" })
            </div>
            <input type="submit" name="Button" value="SUBMIT" />
        </div>
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/bootstrap.js")
</body>
</html>

Task23_Low/Views/Questionnaire/UserPassedData.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserPassedData</title>
</head>
<body>
    <div>
        <div>@ViewBag.TextReturn</div>
        <div>@ViewBag.AdressReturn</div>
        <div>@ViewBag.ScalesReturn</div>
        <div>@ViewBag.HornsReturn</div>
        <div>@ViewBag.CityReturn</div>
        <div>@ViewBag.WorkReturn</div>
        <div>@ViewBag.RegionReturn</div>
        <div>@ViewBag.OrganisationReturn</div>
        <div>@ViewBag.EmailReturn</div>
        <div>@ViewBag.CountryReturn</div>
        <div>@ViewBag.ExperienceReturn</div>
        <div>@ViewBag.PositionReturn</div>
    </div>
</body>
</html>